version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: safe-paws-backend
    ports:
      - '3000:3000'
    command: npm run start
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: safe-paws-frontend
    ports:
      - '4173:4173'
    command: npm run start