POST http://localhost:3000/publications/create
content-type: application/json

{
    "title": "Plataform",
    "description": "Enjoy your vacations in a plataform in the middle of nowhere!",
    "location": "Principality of Sealand",
    "pets": [
        {"Sharky": "shark"},
        {"Smoothie": "shark"}
    ],
    "contact": "ilovesharks@sealandofficial.com"
}

###
